# Generated by Django 3.1 on 2021-04-11 10:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0002_auto_20201204_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='compnay',
        ),
        migrations.RemoveField(
            model_name='job',
            name='image',
        ),
        migrations.RemoveField(
            model_name='jobcategory',
            name='image',
        ),
        migrations.AlterField(
            model_name='job',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
